#!/bin/bash

# Quick Reference Guide for Temporal Transport Service v3.0.0

echo "=== Temporal Transport Service - Quick Reference ==="
echo ""

echo "📁 NEW FILES CREATED:"
echo "  ✅ utils/holiday_detector.py          - Poya day & time period detection (no CSV)"
echo "  ✅ utils/temporal_features.py         - Survey rules for reliability/crowding (no CSV)"
echo "  ✅ utils/temporal_gnn_model.py        - Temporal-aware GNN architecture"
echo "  ✅ utils/transport_service_gnn_refactored.py - Main service (backward compatible)"
echo "  ✅ train_temporal_gnn.py              - Training script example"
echo "  ✅ REFACTORING_v3.md                  - Detailed documentation"
echo "  ✅ REFACTORING_SUMMARY.md             - Quick overview"
echo ""

echo "📋 DATA FILES:"
echo "  Still needed:"
echo "    ✅ data/nodes.csv                   - Locations"
echo "    ✅ data/services.csv                - Transport services"
echo "    ✅ data/edges.csv                   - Routes"
echo "    ✅ data/timetables.csv              - Schedules (optional)"
echo ""
echo "  No longer needed:"
echo "    ❌ data/calendar.csv                - Replaced by HolidayDetector"
echo "    ❌ data/service_conditions.csv      - Replaced by survey rules"
echo ""

echo "🚀 QUICK START:"
echo ""
echo "1. Test temporal features:"
echo "   python -c 'from utils.holiday_detector import HolidayDetector; d = HolidayDetector(); print(d.get_temporal_features(__import__(\"datetime\").datetime(2025, 12, 8), \"08:00\"))'"
echo ""
echo "2. Test survey rules:"
echo "   python -c 'from utils.temporal_features import get_reliability_score; print(get_reliability_score(\"train\", \"morning\", \"regular\"))'"
echo ""
echo "3. Start service with refactored GNN:"
echo "   uvicorn app:app --reload --port 8001"
echo ""
echo "4. Test API endpoint:"
echo "   curl -X POST http://localhost:8001/api/recommend \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"origin\":\"Colombo\",\"destination\":\"Anuradhapura\",\"departure_date\":\"2025-12-25\",\"departure_time\":\"14:30\"}'"
echo ""

echo "📚 USAGE EXAMPLES:"
echo ""
echo "Example 1: Get temporal features for a date/time"
echo "---"
echo "from utils.holiday_detector import HolidayDetector"
echo "from datetime import datetime"
echo ""
echo "detector = HolidayDetector()"
echo "features = detector.get_temporal_features(datetime(2025, 12, 8), '08:00')"
echo "print(features)"
echo "# Output:"
echo "# {"
echo "#   'day_type': 'poya',"
echo "#   'is_poya': True,"
echo "#   'time_period': 'morning',"
echo "#   'is_crowded_likely': True"
echo "# }"
echo ""

echo "Example 2: Get reliability score from survey data"
echo "---"
echo "from utils.temporal_features import get_reliability_score, get_crowding_score"
echo ""
echo "# What's the reliability of trains on a regular morning?"
echo "score = get_reliability_score('train', 'morning', 'regular')"
echo "print(f'Train reliability at morning on regular day: {score}')"
echo "# Output: Train reliability at morning on regular day: 0.7"
echo ""
echo "# How crowded will it be?"
echo "crowding = get_crowding_score('train', 'morning', 'regular')"
echo "print(f'Crowding: {crowding}')"
echo "# Output: Crowding: 1 (crowded)"
echo ""

echo "Example 3: Get recommendations with temporal context"
echo "---"
echo "from utils.transport_service_gnn_refactored import TransportServiceGNNRefactored"
echo ""
echo "service = TransportServiceGNNRefactored('model/transport_gnn_model.pth', 'data')"
echo ""
echo "result = service.get_recommendations("
echo "    origin='Colombo',"
echo "    destination='Anuradhapura',"
echo "    departure_date='2025-12-25',"
echo "    departure_time='14:30'"
echo ")"
echo ""
echo "print(f'Best mode: {result[\"best_mode\"]}')"
echo "print(f'Top recommendation: {result[\"recommendations\"][0]}')"
echo ""

echo "📊 POYA DAYS (2025):"
echo "  - Jan 13  - February 12  - March 13    - April 12     - May 12"
echo "  - June 10 - July 10      - August 9    - September 7  - October 7"
echo "  - Nov 5   - Dec 5"
echo ""

echo "⏰ TIME PERIODS:"
echo "  - early_morning: 05:00-06:59   (Few services)"
echo "  - morning: 07:00-09:59         (PEAK - crowded)"
echo "  - day: 10:00-15:59             (Normal)"
echo "  - evening: 16:00-18:59         (PEAK - crowded)"
echo "  - night: 19:00-22:59           (Reduced)"
echo "  - late_night: 23:00-04:59      (Very limited)"
echo ""

echo "🎯 MIGRATION FROM v2 TO v3:"
echo ""
echo "OLD CODE:"
echo "  from utils.transport_service_gnn import TransportServiceGNN"
echo ""
echo "NEW CODE (backward compatible):"
echo "  from utils.transport_service_gnn_refactored import TransportServiceGNNRefactored"
echo "  # or use the alias:"
echo "  from utils.transport_service_gnn_refactored import TransportServiceGNN"
echo ""

echo "🧪 TESTING:"
echo ""
echo "1. Test HolidayDetector:"
echo "   python -m pytest tests/ -k holiday -v"
echo ""
echo "2. Test temporal features:"
echo "   python -m pytest tests/ -k temporal -v"
echo ""
echo "3. Test API endpoints:"
echo "   curl http://localhost:8001/"
echo "   curl http://localhost:8001/api/health"
echo "   curl 'http://localhost:8001/api/day-info?date=2025-12-08&time=08:00'"
echo ""

echo "📖 DOCUMENTATION:"
echo "  - REFACTORING_v3.md       - Complete technical documentation"
echo "  - REFACTORING_SUMMARY.md  - Quick overview and migration guide"
echo "  - train_temporal_gnn.py   - Training script example"
echo ""

echo "❓ FAQ:"
echo ""
echo "Q: What if the GNN model isn't trained?"
echo "A: The service will use survey-based rules for recommendations."
echo "   Install the model by running train_temporal_gnn.py"
echo ""
echo "Q: How do I update poya days?"
echo "A: Edit POYA_DAYS_2025 in utils/holiday_detector.py"
echo "   or use HolidayDetector(use_api=True) with external API"
echo ""
echo "Q: How do I change survey rules?"
echo "A: Edit create_survey_based_reliability_rules() in utils/temporal_features.py"
echo ""
echo "Q: Can I still use the old API endpoints?"
echo "A: Yes, they still work but now use temporal awareness"
echo "   /api/query, /api/parse, /api/services all work as before"
echo ""

echo "🔗 API ENDPOINTS:"
echo ""
echo "GET /                           - Service info"
echo "POST /api/query                 - Natural language queries"
echo "POST /api/parse                 - NLP parsing only"
echo "POST /api/services              - Structured query"
echo "POST /api/recommend             - **NEW** Temporal recommendations"
echo "GET /api/day-info              - **NEW** Day information"
echo "GET /api/all-services          - All services"
echo "GET /api/health                - Health check"
echo ""

echo "✅ All set! Start the service with: uvicorn app:app --reload --port 8001"
echo ""
